export const shopCategories = [
  { value: "wedding_planner", label: "Wedding Planner" },
  { value: "venue", label: "Wedding Venue" },
  { value: "catering", label: "Catering Services" },
  { value: "photography", label: "Photography" },
  { value: "videography", label: "Videography" },
  { value: "decoration", label: "Decoration & Styling" },
  { value: "florist", label: "Florist" },
  { value: "bridal_wear", label: "Bridal Wear (Dresses, Gowns)" },
  { value: "groom_wear", label: "Groom Wear (Suits, Tuxedos)" },
  { value: "makeup_artist", label: "Makeup Artist" },
  { value: "hair_stylist", label: "Hair Stylist" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "cake", label: "Wedding Cakes & Desserts" },
  { value: "music_band", label: "Live Band / Musicians" },
  { value: "dj", label: "DJ Services" },
  { value: "mc", label: "MC / Event Host" },
  { value: "car_rental", label: "Wedding Car Rental" },
  { value: "transportation", label: "Guest Transportation" },
  { value: "invitation_cards", label: "Invitation Cards & Printing" },
  { value: "event_rentals", label: "Event Rentals (Chairs, Tents, Tables)" },
  { value: "lighting_sound", label: "Lighting & Sound Services" },
  { value: "security", label: "Event Security Services" },
  { value: "cleaning", label: "Post-Event Cleaning" },
  { value: "honeymoon_planning", label: "Honeymoon Planning" },
  { value: "gift_registry", label: "Gift Registry Services" },
  { value: "dance_lessons", label: "Wedding Dance Lessons" },
  { value: "officiant", label: "Wedding Officiant" },
  { value: "cultural_services", label: "Traditional & Cultural Wedding Services" },
  { value: "tent_decor", label: "Tent & Outdoor Setup" },
  { value: "photo_booth", label: "Photo Booth Services" }
];